version: 2
registries:
  registry-npmjs-org:
    type: npm-registry
    url: https://registry.npmjs.org
    token: '${{secrets.NPM_TOKEN}}'
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    groups:
      internal-deps-minor-and-patch:
        applies-to: version-updates
        patterns:
          - '@alkem/*'
        update-types:
          - 'minor'
          - 'patch'
      external-deps-minor-and-patch:
        applies-to: version-updates
        patterns:
          - '*'
        exclude-patterns:
          - '@alkem/*'
        update-types:
          - 'minor'
          - 'patch'
    registries:
      - registry-npmjs-org
    versioning-strategy: increase
    commit-message:
      prefix: chore(deps)
      prefix-development: chore(dev-deps)
