root: true
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
env:
  browser: true
  es6: true
  node: true
rules:
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/no-empty-function': off
  '@typescript-eslint/explicit-module-boundary-types': off
overrides:
  - files:
      - '**/*.test.ts'
    env:
      jest: true
    rules:
      '@typescript-eslint/ban-types': off
  - files:
      - 'tests/*.spec.js'
      - 'tests/*.expect.js'
    env:
      mocha: true
    globals:
      cy: true
      Cypress: true
    rules:
      '@typescript-eslint/no-var-requires': off
  - files:
      - 'scripts.js'
      - 'tests/esm.server.js'
    env:
      node: true
    rules:
      '@typescript-eslint/no-var-requires': off
