parser: 'babel-eslint'
env:
  browser: true
  es6: true
  node: true
extends: 'eslint:recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules: {}
overrides:
  - files:
      - '**/*.test.js'
    env:
      jest: true
  - files:
      - '**/*.spec.js'
      - '**/*.expect.js'
    env:
      mocha: true
    globals:
      cy: true
      Cypress: true
